name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@main
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          organization: "${{ github.event.repository.owner.login }}"
          repository: "goodstuff"
          login: "${{ secrets.ALI_DOCKERHUB_USERNAME }}"
          password: "${{ secrets.ALI_DOCKERHUB_PASSWORD }}"
          platforms: linux/amd64,linux/arm64
        

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}
